# Generated by Django 5.0.1 on 2024-01-23 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('token', models.CharField(max_length=100)),
                ('ref_id', models.CharField(max_length=100)),
                ('card_pan', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('date_created', models.CharField(default=django.utils.timezone.now, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.viplevel')),
            ],
        ),
    ]
